"""making tables

Revision ID: 927440350895
Revises: 08ff8d0d9e06
Create Date: 2023-04-04 21:07:59.528804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '927440350895'
down_revision = '08ff8d0d9e06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original', sa.Boolean(), nullable=False))
        batch_op.drop_column('made_up')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('made_up', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('original')

    # ### end Alembic commands ###
